name: Python Tests

on: [push]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install tox

      - name: Validate formatting
        run: tox -e format

  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        tox_env:
          - py38-django42
          - py312-django42
          - py312-django50
          - py312-django51
        include:
          - python-version: 3.8
            tox_env: py38-django42
          - python-version: 3.12
            tox_env: py312-django42
          - python-version: 3.12
            tox_env: py312-django50
          - python-version: 3.12
            tox_env: py312-django51

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}

        uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.python-version }}"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions

      - name: Test with tox
        run: tox -e ${{ matrix.tox_env }}

      - name: Prepare artifacts
        run: mkdir .coverage-data && mv .coverage.* .coverage-data/
